# Generated by Django 2.2.2 on 2019-12-12 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='follow',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='followrequest',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_pendings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
