# Generated by Django 2.2.2 on 2020-01-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20191224_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckIn',
        ),
    ]
