# Generated by Django 2.2.2 on 2020-01-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='event',
            name='picture_exists',
            field=models.BooleanField(default=False),
        ),
    ]
