# Generated by Django 2.2.2 on 2019-11-08 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20191108_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='check_in_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.Event'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
