# Generated by Django 2.2.2 on 2019-12-05 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20191205_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
    ]
